apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mvowb53pe-go 
  janus-idp.io/tekton: mvowb53pe-go
  backstage.io/kubernetes-id: mvowb53pe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mvowb53pe-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml