apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mvowb53pe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mvowb53pe-go 
  name: mvowb53pe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mvowb53pe-go 
